start_delay: 1
start_commands: >
      cd /colcon_ws/src/verifiable_od/src/lib/depth_clustering &&
      rm -rf build install ;
      cd /colcon_ws/src/verifiable_od/src/lib/depth_clustering/scripts/depth_clustering &&
      source setup.bash --system &&
      cd /colcon_ws/src/verifiable_od/src/lib/depth_clustering/build/amd64/depth_clustering/release &&
      make -j8

ros:
  workspace: /colcon_ws
  ros_package: verifiable_od
  ros2_run_nodes:
  - verifiable_od_node
